version: "3.3"
services:

  mysql-local:
    image: mysql:8.0.17
    environment:
      MYSQL_ROOT_PASSWORD: career_jumpstart
      MYSQL_DATABASE: career_jumpstart
    ports:
      - "3308:3306"

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 9090:80
    environment:
      - PMA_ARBITRARY=1