version: "3.3"
services:
  mysql-local:
    image: mariadb:10.7.3 #mysql currently doesn't work for ARM64
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT

  phpmyadmin:
    image: phpmyadmin
    platform: linux/x86_64
    restart: always
    ports:
      - 9090:80
    environment:
      - PMA_ARBITRARY=1